# Generated by Django 5.0.2 on 2024-02-23 20:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cc', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('date_of_hire', models.DateField(default=datetime.date(2024, 2, 23))),
                ('created_date', models.DateField(auto_now_add=True)),
                ('salary', models.PositiveIntegerField()),
                ('state', models.BooleanField(default=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='employs')),
            ],
            options={
                'verbose_name_plural': 'employes',
                'db_table': 'employ',
            },
        ),
    ]
