# Generated by Django 5.0.2 on 2024-02-23 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employ',
            name='gender',
            field=models.CharField(choices=[('Male', 'M'), ('Female', 'F')], default='Male', max_length=10),
        ),
    ]
