# Generated by Django 5.0.2 on 2024-02-26 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0003_tipo_alter_employ_date_of_hire_employ_employ_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='employ',
            name='cat',
            field=models.ManyToManyField(related_name='category', to='fac.category'),
        ),
    ]
