# Generated by Django 5.0.2 on 2024-02-26 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0004_category_employ_cat'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
        migrations.AlterModelTable(
            name='tipo',
            table='tipo',
        ),
    ]
